 Tue, 10 Mar 2020 16:07:23  INFO test_login.py setUpClass [ line:40 ] ==================== 准备开始执行登录接口测试 ====================
 Tue, 10 Mar 2020 16:07:24  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 16:07:24  INFO test_login.py test_login [ line:77 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 16:07:24  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '150 71369970', 'pwd': '123456'}
 Tue, 10 Mar 2020 16:07:24  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 16:07:25  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '18379169674', 'pwd': '1234568'}
 Tue, 10 Mar 2020 16:07:25  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 16:07:25  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '', 'pwd': '1234568'}
 Tue, 10 Mar 2020 16:07:25  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'},测试通过
 Tue, 10 Mar 2020 16:07:26  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': ''}
 Tue, 10 Mar 2020 16:07:26  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'},测试通过
 Tue, 10 Mar 2020 16:07:26  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234569'}
 Tue, 10 Mar 2020 16:07:27  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Tue, 10 Mar 2020 16:07:27  INFO test_login.py tearDownClass [ line:46 ] ==================== 登录接口测试执行完毕====================
 Tue, 10 Mar 2020 16:07:27  INFO test_recharge.py setUpClass [ line:41 ] ==================== 准备开始执行充值接口测试 ====================
 Tue, 10 Mar 2020 16:07:27  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 16:07:27  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 16:07:28  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '200'}
 Tue, 10 Mar 2020 16:07:28  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '9379.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '充值成功'}, 实际结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '9379.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '充值成功'},测试通过
 Tue, 10 Mar 2020 16:07:29  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13248183622', 'amount': '200'}
 Tue, 10 Mar 2020 16:07:29  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'}, 实际结果是：{'status': 0, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'},测试通过
 Tue, 10 Mar 2020 16:07:29  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13523', 'amount': '201'}
 Tue, 10 Mar 2020 16:07:29  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Tue, 10 Mar 2020 16:07:30  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '', 'amount': '201'}
 Tue, 10 Mar 2020 16:07:30  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'},测试通过
 Tue, 10 Mar 2020 16:07:30  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': ''}
 Tue, 10 Mar 2020 16:07:30  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20115', 'data': None, 'msg': '请输入金额'}, 实际结果是：{'status': 0, 'code': '20115', 'data': None, 'msg': '请输入金额'},测试通过
 Tue, 10 Mar 2020 16:07:31  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '20.098'}
 Tue, 10 Mar 2020 16:07:31  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'}, 实际结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'},测试通过
 Tue, 10 Mar 2020 16:07:31  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '-30'}
 Tue, 10 Mar 2020 16:07:31  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 16:07:32  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '1000000'}
 Tue, 10 Mar 2020 16:07:32  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 16:07:32  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '哈哈'}
 Tue, 10 Mar 2020 16:07:32  INFO test_recharge.py test_recharge [ line:80 ] 预期结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'}, 实际结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'},测试通过
 Tue, 10 Mar 2020 16:07:33  INFO test_recharge.py tearDownClass [ line:47 ] ==================== 充值接口测试接口测试执行完毕====================
 Tue, 10 Mar 2020 16:07:33  INFO test_register1.py setUpClass [ line:55 ] ==================== 准备开始执行注册接口测试 ====================
 Tue, 10 Mar 2020 16:07:33  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13351184590', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:33  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:34  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '14977834828', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:34  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:34  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15399311089', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:34  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:35  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17338151299', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:35  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:35  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17722485985', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:35  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:36  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18043369005', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:36  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:36  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18117009644', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:36  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:37  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18961350373', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:37  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:37  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '19940982101', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:37  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:38  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13014008712', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:38  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:38  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13136977760', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:39  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:39  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13275267473', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:39  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:40  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '14563350349', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:40  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:40  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15579640482', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:40  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:41  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15646288532', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:41  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:41  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '16609960385', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:41  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:42  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17104272159', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:42  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:42  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17597183972', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:42  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:43  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17644320195', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:43  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:43  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18532418327', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:43  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:44  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18622422923', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:44  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:44  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '16677312572', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:44  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:45  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13408307388', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:45  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:45  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13500115504', 'pwd': '1234567', 'regname': 'user1'}
 Tue, 10 Mar 2020 16:07:45  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:46  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13619993659', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 16:07:46  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:46  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13704212361', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 16:07:46  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:47  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13868581059', 'pwd': '1234567', 'regname': 'user3'}
 Tue, 10 Mar 2020 16:07:47  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:47  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13927626651', 'pwd': '1234567', 'regname': 'user3'}
 Tue, 10 Mar 2020 16:07:47  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:48  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '14780289559', 'pwd': '1234567', 'regname': 'user4'}
 Tue, 10 Mar 2020 16:07:48  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:48  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15097813973', 'pwd': '1234567', 'regname': 'user4'}
 Tue, 10 Mar 2020 16:07:48  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:49  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15184393352', 'pwd': '1234567', 'regname': 'user5'}
 Tue, 10 Mar 2020 16:07:49  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:49  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15212678370', 'pwd': '1234567', 'regname': 'user5'}
 Tue, 10 Mar 2020 16:07:50  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:50  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15740269064', 'pwd': '1234567', 'regname': 'user6'}
 Tue, 10 Mar 2020 16:07:50  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:50  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15876020093', 'pwd': '1234567', 'regname': 'user6'}
 Tue, 10 Mar 2020 16:07:51  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:51  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '15945377583', 'pwd': '1234567', 'regname': 'user7'}
 Tue, 10 Mar 2020 16:07:51  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:52  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17275715852', 'pwd': '1234567', 'regname': 'user7'}
 Tue, 10 Mar 2020 16:07:52  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:52  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '17871852519', 'pwd': '1234567', 'regname': 'user8'}
 Tue, 10 Mar 2020 16:07:52  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:53  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18279131709', 'pwd': '1234567', 'regname': 'user8'}
 Tue, 10 Mar 2020 16:07:53  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:53  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18386363844', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 16:07:53  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:54  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18499524581', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 16:07:54  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:54  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18700825660', 'pwd': '1234567', 'regname': 'user8'}
 Tue, 10 Mar 2020 16:07:54  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:55  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18872106069', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 16:07:55  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:55  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18988240739', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 16:07:55  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Tue, 10 Mar 2020 16:07:56  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '19276221589', 'pwd': '1234567', 'regname': 'user9'}
 Tue, 10 Mar 2020 16:07:56  ERROR test_register1.py test_register [ line:90 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_register1.py", line 87, in test_register
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'} != {'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
- {'code': '10001', 'data': None, 'msg': '注册成功', 'status': 1}
?             ^^^                         ^^^^             ^

+ {'code': '20109', 'data': None, 'msg': '手机号码格式不正确', 'status': 0}
?           ++  ^                         ^^^^^^^^^             ^

 Tue, 10 Mar 2020 16:07:57  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 16:07:57  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20110", "data":None, "msg":"手机号码已被注册"}, 实际结果是：{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'},测试通过
 Tue, 10 Mar 2020 16:07:57  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '', 'pwd': '1234567', 'regname': 'user2'}
 Tue, 10 Mar 2020 16:07:57  INFO test_register1.py test_register [ line:94 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'},测试通过
 Tue, 10 Mar 2020 16:07:58  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13013631682', 'pwd': '', 'regname': 'user2'}
 Tue, 10 Mar 2020 16:07:58  INFO test_register1.py test_register [ line:94 ] 预期结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}, 实际结果是：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'},测试通过
 Tue, 10 Mar 2020 16:07:58  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18213184879', 'pwd': '123', 'regname': 'user3'}
 Tue, 10 Mar 2020 16:07:58  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20108", "data":None, "msg":"密码长度必须为6~18"}, 实际结果是：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'},测试通过
 Tue, 10 Mar 2020 16:07:59  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '1389087', 'pwd': '1234567', 'regname': 'user3'}
 Tue, 10 Mar 2020 16:07:59  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20109", "data":None, "msg":"手机号码格式不正确"}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Tue, 10 Mar 2020 16:07:59  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18374005499', 'pwd': '哈哈', 'regname': 'user3'}
 Tue, 10 Mar 2020 16:07:59  INFO test_register1.py test_register [ line:94 ] 预期结果是：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}, 实际结果是：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'},测试通过
 Tue, 10 Mar 2020 16:07:59  INFO test_register1.py tearDownClass [ line:61 ] ==================== 注册接口测试执行完毕====================
 Tue, 10 Mar 2020 16:07:59  INFO test_withdraw.py setUpClass [ line:40 ] ==================== 准备开始执行登录接口测试 ====================
 Tue, 10 Mar 2020 16:08:00  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Tue, 10 Mar 2020 16:08:00  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Tue, 10 Mar 2020 16:08:00  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13859429047', 'amount': '1'}
 Tue, 10 Mar 2020 16:08:01  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 1, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'}, 实际结果是：{'status': 1, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'},测试通过
 Tue, 10 Mar 2020 16:08:01  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '1098', 'amount': '1'}
 Tue, 10 Mar 2020 16:08:01  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Tue, 10 Mar 2020 16:08:01  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '1'}
 Tue, 10 Mar 2020 16:08:02  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '9378.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '取现成功'}, 实际结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '9378.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '取现成功'},测试通过
 Tue, 10 Mar 2020 16:08:02  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '20.098'}
 Tue, 10 Mar 2020 16:08:02  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'}, 实际结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'},测试通过
 Tue, 10 Mar 2020 16:08:03  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '-30'}
 Tue, 10 Mar 2020 16:08:03  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 16:08:03  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '哈哈'}
 Tue, 10 Mar 2020 16:08:03  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'}, 实际结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'},测试通过
 Tue, 10 Mar 2020 16:08:04  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '5000000'}
 Tue, 10 Mar 2020 16:08:04  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Tue, 10 Mar 2020 16:08:04  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '10378'}
 Tue, 10 Mar 2020 16:08:05  INFO test_withdraw.py test_login [ line:81 ] 预期结果是：{'status': 1, 'code': '20119', 'data': None, 'msg': '余额不足，请修改提现额度'}, 实际结果是：{'status': 1, 'code': '20119', 'data': None, 'msg': '余额不足，请修改提现额度'},测试通过
 Tue, 10 Mar 2020 16:08:05  INFO test_withdraw.py tearDownClass [ line:46 ] ==================== 登录接口测试执行完毕====================
