 Mon, 09 Mar 2020 21:30:14  INFO test_login.py setUpClass [ line:40 ] ==================== 准备开始执行登录接口测试 ====================
 Mon, 09 Mar 2020 21:30:14  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Mon, 09 Mar 2020 21:30:14  INFO test_login.py test_login [ line:77 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Mon, 09 Mar 2020 21:30:14  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '150 71369970', 'pwd': '123456'}
 Mon, 09 Mar 2020 21:30:14  INFO test_login.py test_login [ line:77 ] 预期结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}, 实际结果是：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'},测试通过
 Mon, 09 Mar 2020 21:30:14  INFO test_login.py tearDownClass [ line:46 ] ==================== 登录接口测试执行完毕====================
 Mon, 09 Mar 2020 21:30:14  INFO test_recharge.py setUpClass [ line:41 ] ==================== 准备开始执行充值接口测试 ====================
 Mon, 09 Mar 2020 21:30:14  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/login， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567'}
 Mon, 09 Mar 2020 21:30:15  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"登录成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'},测试通过
 Mon, 09 Mar 2020 21:30:15  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '200'}
 Mon, 09 Mar 2020 21:30:15  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '4600.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '充值成功'}, 实际结果是：{'status': 1, 'code': '10001', 'data': {'id': 1507, 'regname': 'user1', 'pwd': 'FCEA920F7412B5DA7BE0CF42B8C93759', 'mobilephone': '13941387738', 'leaveamount': '4600.00', 'type': '1', 'regtime': '2020-03-09 14:25:05.0'}, 'msg': '充值成功'},测试通过
 Mon, 09 Mar 2020 21:30:15  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13296245779', 'amount': '200'}
 Mon, 09 Mar 2020 21:30:15  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{'status': 0, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'}, 实际结果是：{'status': 0, 'code': '20104', 'data': None, 'msg': '此手机号对应的会员不存在'},测试通过
 Mon, 09 Mar 2020 21:30:15  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13523', 'amount': '201'}
 Mon, 09 Mar 2020 21:30:15  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Mon, 09 Mar 2020 21:30:15  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '20.098'}
 Mon, 09 Mar 2020 21:30:15  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'}, 实际结果是：{'status': 0, 'code': '20116', 'data': None, 'msg': '输入金额的金额小数不能超过两位'},测试通过
 Mon, 09 Mar 2020 21:30:16  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '-30'}
 Mon, 09 Mar 2020 21:30:16  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'}, 实际结果是：{'status': 0, 'code': '20117', 'data': None, 'msg': '请输入范围在0到50万之间的正数金额'},测试通过
 Mon, 09 Mar 2020 21:30:16  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/recharge， 请求参数：{'mobilephone': '13941387738', 'amount': '哈哈'}
 Mon, 09 Mar 2020 21:30:16  INFO test_recharge.py test_recharge [ line:82 ] 预期结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'}, 实际结果是：{'status': 0, 'code': '20118', 'data': None, 'msg': '请输入数字'},测试通过
 Mon, 09 Mar 2020 21:30:16  INFO test_recharge.py tearDownClass [ line:47 ] ==================== 充值接口测试接口测试执行完毕====================
 Mon, 09 Mar 2020 21:30:16  INFO test_register1.py setUpClass [ line:55 ] ==================== 准备开始执行注册接口测试 ====================
 Mon, 09 Mar 2020 21:30:16  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18353831125', 'pwd': '1234567', 'regname': 'user1'}
 Mon, 09 Mar 2020 21:30:16  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Mon, 09 Mar 2020 21:30:16  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18562300524', 'pwd': '1234567', 'regname': 'user1'}
 Mon, 09 Mar 2020 21:30:17  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Mon, 09 Mar 2020 21:30:17  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13931126814', 'pwd': '1234567', 'regname': 'user1'}
 Mon, 09 Mar 2020 21:30:17  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":1,  "code":"10001", "data":None, "msg":"注册成功"}, 实际结果是：{'status': 1, 'code': '10001', 'data': None, 'msg': '注册成功'},测试通过
 Mon, 09 Mar 2020 21:30:17  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '13941387738', 'pwd': '1234567', 'regname': 'user2'}
 Mon, 09 Mar 2020 21:30:17  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20110", "data":None, "msg":"手机号码已被注册"}, 实际结果是：{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'},测试通过
 Mon, 09 Mar 2020 21:30:17  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '18297908147', 'pwd': '123', 'regname': 'user3'}
 Mon, 09 Mar 2020 21:30:17  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20108", "data":None, "msg":"密码长度必须为6~18"}, 实际结果是：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'},测试通过
 Mon, 09 Mar 2020 21:30:18  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/register， 请求参数：{'mobilephone': '1389087', 'pwd': '1234567', 'regname': 'user3'}
 Mon, 09 Mar 2020 21:30:18  INFO test_register1.py test_register [ line:94 ] 预期结果是：{"status":0,  "code":"20109", "data":None, "msg":"手机号码格式不正确"}, 实际结果是：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'},测试通过
 Mon, 09 Mar 2020 21:30:18  INFO test_register1.py tearDownClass [ line:61 ] ==================== 注册接口测试执行完毕====================
 Mon, 09 Mar 2020 21:30:18  INFO test_withdraw.py setUpClass [ line:40 ] ==================== 准备开始执行登录接口测试 ====================
 Mon, 09 Mar 2020 21:30:18  INFO http_request.py request [ line:56 ] 正在发送请求，请求地址：http://118.24.221.133:8081/futureloan/mvc/api/member/withdraw， 请求参数：{'mobilephone': '13941387738', 'amount': '1'}
 Mon, 09 Mar 2020 21:30:19  ERROR test_withdraw.py test_login [ line:73 ] {'status': 1, 'code': '10001', 'data': None, 'msg': '提现成功'} != {'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
- {'code': '10001', 'data': None, 'msg': '提现成功', 'status': 1}
?          ^^^^^^^                        ^^^^             ^

+ {'code': None, 'data': None, 'msg': '抱歉，请先登录。', 'status': 0}
?          ^^^^                        ^^^^^^^^             ^
Traceback (most recent call last):
  File "/Users/huangjie/学习/untitled7/test_cases/test_withdraw.py", line 70, in test_login
    self.assertEqual(eval(case.expected_data), res)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1151, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: {'status': 1, 'code': '10001', 'data': None, 'msg': '提现成功'} != {'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
- {'code': '10001', 'data': None, 'msg': '提现成功', 'status': 1}
?          ^^^^^^^                        ^^^^             ^

+ {'code': None, 'data': None, 'msg': '抱歉，请先登录。', 'status': 0}
?          ^^^^                        ^^^^^^^^             ^

 Mon, 09 Mar 2020 21:30:19  INFO test_withdraw.py tearDownClass [ line:46 ] ==================== 登录接口测试执行完毕====================
